[disk]
llm = "qwen"

[disk.embeddings]
api_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key = "your_api_key"
model = "text-embedding-v4"

[model.openai]
api_url = "https://api.openai.com/v1/engines/davinci/completions"
api_key = "your_api_key"
model = "GPT-5.1"

[model.qwen]
api_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key = "your_api_key"
model = "qwen-plus"

[model.kimi]
api_url = "https://api.kimi.com/v1/engines/kimi/completions"
api_key = "your_api_key"
model = "Kimi-1.0"

[model.ollama]
api_url = "http://localhost:11434/v1/engines/ollama/completions"
model = "Ollama-1.0"